pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - bash: echo "##vso[task.setvariable variable=pkg_version]$(cat package.json | grep version | cut -d ':' -f 2 | tr -d '[ \",]')"
    - task: CmdLine@2
      inputs:
        script: 'npm run build:image'
    - task: CmdLine@2
      inputs:
        script: 'npm run build:withimage'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'homebridge-unraid-$(pkg_version).tgz'
        artifact: 'npm-package'
        publishLocation: 'pipeline'
    - task: CmdLine@2
      inputs:
        script: 'npm run build:publisher -- --build-arg npm_auth_token=$(NpmAuthKey)'
    - task: CmdLine@2
      inputs:
        script: 'npm run release'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))